#!/bin/bash
### BEGIN INIT INFO
# Provides: Vault
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: Mount user vault
# Description: Mount vault.img from /home/demo/Live-usb-storage/sync/vault.img
### END INIT INFO

if [ -e "/home/demo/Live-usb-storage/sync/vault.img" ] ; then
  losetup -fP /home/demo/Live-usb-storage/sync/vault.img
fi
